# Generated by Django 3.2.8 on 2021-10-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sanctuary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
    ]
