# Generated by Django 3.2.8 on 2021-10-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sanctuary', '0002_alter_player_suspended'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
